version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  pysc_default:
    format: '%(asctime)s [%(levelname)s] %(name)s (%(filename)s).%(funcName)s(%(lineno)d) - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: pysc_default
    stream: ext://sys.stdout
  log_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: pysc_default
    filename: pysc.log
    
# loggers:
#   simpleExample:
#     level: DEBUG
#     handlers: [console]
#     propagate: no
root:
  level: DEBUG
  handlers: [log_file]